### ISSUE TITLE
'Must use a valid format name' error for Sesame; Znum forced integer

### ISSUE THREAD

**Issue by phyzicist** [flash-center/opacplot2#12]
When I run:
`opac-convert -i sesame --Znum 8,1 --Xfracs 0.3,0.7 sesame_ascii_water7155-unclassified.ses`

I get the error:
```
Traceback (most recent call last):
  File "/home/feister/anaconda2/bin/opac-convert", line 11, in <module>
    load_entry_point('opacplot2==1.0.0', 'console_scripts', 'opac-convert')()
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_convert.py", line 284, in convert_tables
    input_data['path_in']).eos_dict
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_convert.py", line 137, in __init__
    raise KeyError('Must use valid format name.')
KeyError: 'Must use valid format name.'
[feister@code EOSTables]$ opac-convert -i sesame --Znum 8,1 --Xfracs 0.3,0.7 sesame_ascii_water7155-unclassified.ses
Traceback (most recent call last):
  File "/home/feister/anaconda2/bin/opac-convert", line 11, in <module>
    load_entry_point('opacplot2==1.0.0', 'console_scripts', 'opac-convert')()
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_convert.py", line 284, in convert_tables
    input_data['path_in']).eos_dict
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_convert.py", line 137, in __init__
    raise KeyError('Must use valid format name.')
KeyError: 'Must use valid format name.'
```

Also, when I try to correct it by trying to use a non-integer Znum

`opac-convert -i sesame --Znum 3.3333333 sesame_ascii_water7155-unclassified.ses`

I get the error:

```
Traceback (most recent call last):
  File "/home/feister/anaconda2/bin/opac-convert", line 11, in <module>
    load_entry_point('opacplot2==1.0.0', 'console_scripts', 'opac-convert')()
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_convert.py", line 272, in convert_tables
    input_data = get_input_data()
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_convert.py", line 74, in get_input_data
    args.Znum = [int(num) for num in args.Znum.split(',')]
ValueError: invalid literal for int() with base 10: '3.3333333'
```

Does Znum have to be an int? If so, why?

**Comment by phyzicist** [comment]
Here is another example using opac-error instead of opac-convert, and it still gives the format error:

`opac-error sesame_ascii_water7153-unclassified.ses sesame_ascii_water7154-unclassified.ses --Znum_1 3 --Znum_2 3`

```
Traceback (most recent call last):
  File "/home/feister/anaconda2/bin/opac-error", line 11, in <module>
    load_entry_point('opacplot2==1.0.0', 'console_scripts', 'opac-error')()
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_error.py", line 773, in check_error
    tabnum=input_data['args'].tabnum_1)
  File "/home/feister/anaconda2/lib/python2.7/site-packages/opacplot2/scripts/opac_error.py", line 358, in __init__
    raise KeyError('{} is not a valid format name!'.format(self.form))
KeyError: 'sesame is not a valid format name!'
```
