### ISSUE TITLE
Get SESAME library

### ISSUE THREAD

**Issue by WebyGit** [flash-center/opacplot2#20]
How can I get SESAME library? Hope someone can share with me!
g.webywang@gmail.com

**Comment by PhysicsDan** [comment]
You can request access here: https://www.lanl.gov/org/ddste/aldsc/theoretical/physics-chemistry-materials/sesame-database.php

**Comment by quchongbing** [comment]
Hi could you take a look at the issue that i am suffering from.?
I'm trying to convert sesame eos to ionmix format, but it shows the following error:
---------------------------------------------------------------
(flash) bing@LAPTOP-S0DHE4PP:~/flash$ ls
eos_convert.py           matr_05250_hydrogen.ses
matr_02290_lithium.ses   matr_07831_carbon_liquid.ses
matr_03717_aluminum.ses
(flash) bing@LAPTOP-S0DHE4PP:~/flash$ opac-convert matr_07831_carbon_liquid.ses
numba.vectorize not loaded, will use numpy.vectorize!
Traceback (most recent call last):
  File "/home/bing/.local/bin/opac-convert", line 33, in <module>
    sys.exit(load_entry_point('opacplot2', 'console_scripts', 'opac-convert')())
  File "/home/bing/Downloads/opacplot2-master/opacplot2/scripts/opac_convert.py", line 315, in convert_tables
    input_data['path_in']).eos_dict
  File "/home/bing/Downloads/opacplot2-master/opacplot2/scripts/opac_convert.py", line 138, in __init__
    self.eos_dict = self.handle_dict[args.input]()
  File "/home/bing/Downloads/opacplot2-master/opacplot2/scripts/opac_convert.py", line 170, in sesame_toEosDict
    op = opp.OpgSesame(self.path_in, opp.OpgSesame.SINGLE)
  File "/home/bing/Downloads/opacplot2-master/opacplot2/opg_sesame.py", line 101, in __init__
    self.parse()
  File "/home/bing/Downloads/opacplot2-master/opacplot2/opg_sesame.py", line 111, in parse
    matid = int(header.split()[1])
IndexError: list index out of range
-----------------------------------------------------

I spent a lot of time and can't solve this issue, could please help me with that?
the sesame data if from Helios folder.
![sesame](https://github.com/flash-center/opacplot2/assets/43544495/5ca0555f-d244-4f6d-b98e-186fa02e3392)
